### ISSUE TITLE
Not passing config: "invalid type: null, expected struct SerdeParseConfig"

### ISSUE THREAD

**Issue by konsumer** [konsumer/rawprotorust#7]
Currently, it seems like it's not passing config, which makes it throw.

You can see issue with `npm test`

```
  console.error
    panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected struct SerdeParseConfig", line: 1, column: 4)', src/lib.rs:12:59

    Stack:

    Error:
        at imports.wbg.__wbg_new_693216e109162396 (/Users/konsumer/Documents/work/rawproto-wasm/target/web/rawproto.js:195:19)
        at console_error_panic_hook::hook::h51ddedfd14848316 (wasm://wasm/001da41e:1:323074)
        at core::ops::function::Fn::call::hf3855f3e0c0b4e53 (wasm://wasm/001da41e:1:383366)
        at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (wasm://wasm/001da41e:1:361815)
        at std::panicking::begin_panic_handler::{{closure}}::h888144d5e9a03cec (wasm://wasm/001da41e:1:371034)
        at std::sys_common::backtrace::__rust_end_short_backtrace::h81961607fd97e28e (wasm://wasm/001da41e:1:382298)
        at rust_begin_unwind (wasm://wasm/001da41e:1:379472)
        at core::panicking::panic_fmt::h4ca53049f45e3264 (wasm://wasm/001da41e:1:380386)
        at core::result::unwrap_failed::h6d050dbd00b66340 (wasm://wasm/001da41e:1:371992)
        at parse_raw (wasm://wasm/001da41e:1:127376)
```

I `console.log` `cfg` input on `parseRaw`:

```
CONFIG { no_fixed64: false, no_fixed32: false }
```

**Comment by konsumer** [comment]
The serde config conversion stuff looks good to me, so I have no idea what the issue is.

**Comment by konsumer** [comment]
Even if I remove config from exposed params:

```rs
#[wasm_bindgen]
pub fn parse_raw(bytes: &[u8], js_path: &str) -> JsValue {
    console_error_panic_hook::set_once();
    let query = SelectQuery::parse(js_path).unwrap();
    let cfg = ParseConfig { no_fixed64: true, no_fixed32: true };

    match try_parse_entries(bytes, cfg) {
        Some(entries) => {
            let mut ret: Vec<SerdeEntry> = vec![];
            for entry in entries.into_iter().filter(|e| is_selected(e, &query)) {
                ret.push(entry.into());
            }
            JsValue::from_serde(&ret).unwrap()
        }
        None => {
            panic!("Input bytes is not a valid protobuf serialization");
        }
    }
}
```

I still get this error, on the test that used to work:

```
 panicked at 'Input bytes is not a valid protobuf serialization', src/lib.rs:23:13
```

```js
const test1 = Buffer.from('\x12\x07Unknown')

test('basic parsing', async () => {
  expect(await parseRaw(test1)).toMatchSnapshot()
  expect(await parseRaw(test2)).toMatchSnapshot()
})
```

So, I think something is broken with serde/bindgen passing values to params.
